import turtle
elva = turtle.Turtle()
elva.shape('turtle')
elva.color('sky blue')
elva.pensize(5)
elva.forward(100)
elva.left(90)
elva.forward(100)
joyce = turtle.Turtle()
joyce.shape('turtle')
joyce.color('blue')
joyce.pensize(5)
joyce.backward(100)
joyce.left(90)
joyce.forward(100)
turtle.done()
